MODELS_PATH: "./harmonization_exps/models"
EXPS_PATH: "./harmonization_exps"

HFLICKR_PATH: "/S4/MI/xueb/data/IDIH/HFlickr"
HDAY2NIGHT_PATH: "/S4/MI/xueb/data/IDIH/Hday2night"
HCOCO_PATH: "/S4/MI/xueb/data/IDIH/HCOCO"
HADOBE5K_PATH: "/S4/MI/xueb/data/IDIH/HAdobe5k_resized"
HADOBE5K_RS_PATH: "/S4/MI/xueb/data/IDIH/HAdobe5k"
HADOBE5K_2048_PATH: "/S4/MI/xueb/data/IDIH/HAdobe5k_resized2048_2048"
HADOBE5K_1024_PATH: "/S4/MI/xueb/data/IDIH/HAdobe5k_resized1024_1024"

IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
